In [2]:
import numpy as np

In [6]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [11]:
np.ones([3,2],dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
X=np.arange(4,dtype=int)
# X.shape
# X.size
np.ones_like(X)


array([1, 1, 1, 1])

In [20]:
X=np.arange(4,dtype=int)
np.zeros_like(X)

array([0, 0, 0, 0])

In [26]:
np.ones([4,4], dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [29]:
X=np.array([[1,2,3],[2,3,4]],dtype=int)
np.ones_like(X)*7

array([[7, 7, 7],
       [7, 7, 7]])

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.rand(3,3,3)

array([[[0.95221575, 0.43523886, 0.24422385],
        [0.77039377, 0.39860908, 0.41766584],
        [0.64102488, 0.27779455, 0.15206025]],

       [[0.84553883, 0.69670038, 0.29149959],
        [0.62252363, 0.60298539, 0.70121752],
        [0.99167374, 0.62702936, 0.68332097]],

       [[0.85889733, 0.66204238, 0.51202989],
        [0.87436754, 0.76282599, 0.97504579],
        [0.66881339, 0.57084902, 0.01463642]]])

In [49]:
np.random.rand(3,3,3)

array([[[ 0.32298418, -0.65401747, -0.45451922],
        [-0.0034649 , -0.25321674, -0.50786924],
        [ 0.40444741, -0.09299365,  0.22333675]],

       [[-0.00377321,  1.55609856,  0.12818066],
        [-1.29336675,  0.59216125,  0.24386669],
        [ 1.37115144,  0.3579236 , -0.71820569]],

       [[-1.16211838,  0.22694464, -0.46199529],
        [ 1.20181335, -0.60358014, -2.53311567],
        [ 0.23314429,  0.07629707, -0.38190844]]])

In [52]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [53]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 2131855602032
[5 2 3] 2132414028736


In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])